### PR TITLE
Support react native

### PR DESCRIPTION
**Pull request by skout90**
modify read me.
react native check.

### CODE REVIEW

**Comment by stuyam** [comment]
Thank you for this awesome pull request! I will merge this. I just so happen to be in the middle of a big update / rebuild of this project and one big portion of that is the ability to give it the default element (or no element at all) to wrap the message and should make a lot of this easier to use going forward.

**Comment by stuyam** [comment]
Now what I am looking at it, do you think the default option for React Native should be something like this?
```
React.createElement(Text, [], message);
```

**Comment by skout90** [comment]
I think that if validator return raw message not element, It can be more flexible.
I can use `styled component`, `glamours`, `emotion` etc..
Is there a advantage of creating Element?

**Comment by stuyam** [comment]
Sounds good to me, I have never used React Native but I support that. Merging... thanks again!

**Pull request merged**
