### PR TITLE
Adding default custom errors messages

### PR DESCRIPTION
**Pull request by rek**
Had a use case where I needed one custom error message for all validation rule errors for a field.

My solution is something like this.

### CODE REVIEW

**Comment by stuyam** [comment]
@rek can you give an example of how this is used?

**Comment by rek** [comment]
Here is how I use it:

```
validator.message(
	'number',
	model.get('number'),
	'required|integer|min:15|max:16',
	'form__errorlist filled',
	'Invalid Length'
)
```
(as opposed to having to have a custom error for each validation rule)

If you are happy with this, then I can add an example into the readme.

The other option I guess is to add a default, which would be more flexible, eg:

```
validator.message(
	'number',
	model.get('number'),
	'required|integer|min:15|max:16',
	'form__errorlist filled',
	{default: 'Invalid Length', min: 'Too short!'}
)
```

**Comment by stuyam** [comment]
Ahhh I see, so if you want the input to always return the same message regardless of what type of error it is. I like that, but yeah if you could update the docs on that with this PR that would be great.

**Comment by rek** [comment]
Ok have added.

**Comment by stuyam** [comment]
Looks good to me! Shipping... 🚢

**Comment by rek** [comment]
Thanks! (and sorry about the typos, i'm sure I read that like 5 times before committing)

**Pull request merged**
