### PR TITLE
method to get error messages

### PR DESCRIPTION
**Pull request by neroze**
method to get error messages

### CODE REVIEW

**Comment by stuyam** [comment]
What is the goal of this pull request? How would it be used?

**Comment by neroze** [comment]
so use case is like.
**Case 1**
I have long page with two section, first section is form and second is with some extra info where I do not required any validation but it is part of my form. So when ever there is validation error and if I am in my second section of my form then it seems unusual that I can not submit form because I can not see validation error. It will easy if I can show validation error in my toast notification as well rather than just in form field.

**Case 2**
I need to show custom validation error message to user or log most often occurring validation error.

**Comment by stuyam** [comment]
@neroze I made some changes to your branch, will you test and make sure those work the way you expect?

Side note, congrats on making your first pull request on GitHub! Happy you make it on our project :)

**Comment by neroze** [comment]
@stuyam works perfect. 
Thank you so much.
Cheers

**Comment by stuyam** [comment]
Looks good, will be in next release

**Comment by neroze** [comment]
Hi mate,

Hope you doing all good. Just wondering if you do not mind adding me as
contributor for simple-react-validator will be awesome.

Cheers

**Pull request merged**
